### PR TITLE
Published posts bug fixes

### PR DESCRIPTION
**Pull request by spacedmonkey**
This is a pretty simple pull request to address some issues #1 #2 

Key code changes
- Ajax only searches for published posts to stop drafts being in collections
- `get_post_collection` function now checks if post exists and it published
- Uses the `wp_send_json`. 

fix https://github.com/TimeIncUK/keystone/issues/382

### CODE REVIEW

**Comment by spacedmonkey** [comment]
Any chance on getting this merged?

**Comment by johnbillion** [comment]
This looks sane. I'll test properly tonight.

Aside: You'll probably want to change the Composer URL for this repo in Keystone to your TimeIncUK fork.

**Comment by spacedmonkey** [comment]
We already have a workaround for this here https://github.com/TimeIncUK/keystone-theme/commit/30c2d3f6125bdadeb944441bf7b28e626cf39e2e

I would prefer to fix this for everyone anyway. This has been a issue since launch, I can wait for this to be merged.

**Comment by spacedmonkey** [comment]
Is there any movement on this? It has been nearly 2 months...

**Pull request closed without merging**
